name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: install k8s
        run: |
          curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=777 sh -
          cat /etc/rancher/k3s/k3s.yaml
          mkdir -p ~/.kube
          cp /etc/rancher/k3s/k3s.yaml ~/.kube/config

      - name: install operator
        shell: bash
        run: |
          make install --debug=b
          make run --debug=b & 
          
      - name: install 2
        shell: bash
        run: |
          sleep 10 &&
          kubectl apply -f ./config/samples/
